### ISSUE TITLE
How do I run this app? (lol)

### ISSUE THREAD

**Issue by StupidRepo** [njt1982/minecraft-item-browser#17]
__

**Comment by njt1982** [comment]
@StupidRepo it's built by Github Actions and deployed to Github Pages (hosted here: https://njt1982.github.io/minecraft-item-browser/#/)

To run it locally, `git clone` the repo, then `yarn install` and finally `yarn run serve`.

I should probably add a README...

**Comment by StupidRepo** [comment]
Yeah, thanks!
